name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: cmake --build build --target test -- ARGS=--verbose

    - name: Test if business.cpp actually present
      run: test -f business.cpp

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: business-mediator-executable
        path: build/
